SIZE = 70

POPULATION_SIZE = 100
GENERATIONS = 100

MUTATION_PROB = 0.05
MUTATION_SIZE = 0.1

CROSSOVER_PROB = 0.7
CROSSOVER_MAXIMUM_SEGMENTS = 3
# CROSSOVER_POINT_MARGIN = 0.2

TOURNAMENT_BATCH_SIZE = 3

MAXIMUM_DAY_WORK = 60 * 60
